theme = "github_light"

[editor]
line-number = "relative"
auto-save = true
bufferline = "multiple"
color-modes = true
soft-wrap = { enable = true }
completion-replace = true

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.whitespace]
# render = "all"

[keys.normal]
A-s = ":w"
"A-c" = ":clipboard-yank"
C-y = ":sh zellij run -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh"
